tx_timeout = "15s"
tps_per_actor = 50
account_dust_amount = 0.0001

[networks.op-inu]
block_time = "1s"
# rpc_url = "ws://op-inu.astar.network:8546"
rpc_url = "ws://op-inu.astar.network:8546"
default = true

[networks.local]
rpc_url = "ws://localhost:8545"
block_time = "2s"
