tx_timeout = "15s"
tps_per_actor = 50
gas_multiplier = 1.51

# [transactions]
# ERC721Deploy =  0.125
# ERC1155Deploy = 0.125

[networks.op-inu]
block_time = "1s"
rpc_url = "ws://op-inu.astar.network:8546"
organic_address = "0x9f7ddec24dd21b41d3cc87330f860e4d8dad10ed"
default = true

[networks.local]
rpc_url = "ws://localhost:8545"
block_time = "2s"
