[package]
name = "inu"
version = "0.1.0"
edition = "2021"
default-run = "inu"

[dependencies]
alloy = { workspace = true }
chrono = "0.4.38"
eyre = { workspace = true }
futures-util = "0.3.30"
rand = { workspace = true }
# ethers = { workspace = true }
# ethers-solc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = "0.1.15"
